use indexmap::IndexMap;
use serde_repr::{Deserialize_repr, Serialize_repr};
use std::sync::LazyLock;

// Original: packages/protocol/src/error-codes.ts, ErrorCode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr)]
#[repr(i64)]
pub enum ErrorCode {
    Success = 0,
    ValidationFailed = 40001,
    RequestMalformed = 40002,
    AuthProvisioningRequired = 40110,
    AuthTokenMissing = 40111,
    AuthTokenUnauthorized = 40112,
    AuthModelNotResolved = 40113,
    SessionNotFound = 40401,
    PromptNotFound = 40402,
    MessageNotFound = 40403,
    ApprovalNotFound = 40404,
    QuestionNotFound = 40405,
    TaskNotFound = 40406,
    FileNotFound = 40407,
    McpServerNotFound = 40408,
    FsPathNotFound = 40409,
    WorkspaceNotFound = 40410,
    FsPermissionDenied = 40411,
    ProviderNotFound = 40412,
    ModelNotFound = 40413,
    TerminalNotFound = 40414,
    SkillNotFound = 40415,
    SessionBusy = 40901,
    ApprovalAlreadyResolved = 40902,
    PromptAlreadyCompleted = 40903,
    TaskAlreadyFinished = 40904,
    McpAlreadyConnected = 40905,
    FsIsDirectory = 40906,
    FsIsBinary = 40907,
    FsGitUnavailable = 40908,
    QuestionDismissed = 40909,
    CompactionUnable = 40910,
    SessionUndoUnavailable = 40911,
    SkillNotActivatable = 40912,
    GoalAlreadyExists = 40913,
    GoalNotFound = 40914,
    GoalStatusInvalid = 40915,
    GoalNotResumable = 40916,
    GoalObjectiveEmpty = 40917,
    GoalObjectiveTooLong = 40918,
    FsAlreadyExists = 40919,
    GoalUnsupportedAgent = 40920,
    ApprovalExpired = 41001,
    QuestionExpired = 41002,
    FileExpired = 41003,
    FileTooLarge = 41301,
    FsTooLarge = 41302,
    FsTooManyResults = 41303,
    FsPathEscapesSession = 41304,
    FsGrepTimeout = 41305,
    FsWatchLimitExceeded = 42902,
    InternalError = 50001,
    PersistenceFailure = 50003,
    ToolExecutionFailed = 60001,
    ToolNotAvailable = 60002,
}

impl ErrorCode {
    pub const ALL: [Self; 55] = [
        Self::Success,
        Self::ValidationFailed,
        Self::RequestMalformed,
        Self::AuthProvisioningRequired,
        Self::AuthTokenMissing,
        Self::AuthTokenUnauthorized,
        Self::AuthModelNotResolved,
        Self::SessionNotFound,
        Self::PromptNotFound,
        Self::MessageNotFound,
        Self::ApprovalNotFound,
        Self::QuestionNotFound,
        Self::TaskNotFound,
        Self::FileNotFound,
        Self::McpServerNotFound,
        Self::FsPathNotFound,
        Self::WorkspaceNotFound,
        Self::FsPermissionDenied,
        Self::ProviderNotFound,
        Self::ModelNotFound,
        Self::TerminalNotFound,
        Self::SkillNotFound,
        Self::SessionBusy,
        Self::ApprovalAlreadyResolved,
        Self::PromptAlreadyCompleted,
        Self::TaskAlreadyFinished,
        Self::McpAlreadyConnected,
        Self::FsIsDirectory,
        Self::FsIsBinary,
        Self::FsGitUnavailable,
        Self::QuestionDismissed,
        Self::CompactionUnable,
        Self::SessionUndoUnavailable,
        Self::SkillNotActivatable,
        Self::GoalAlreadyExists,
        Self::GoalNotFound,
        Self::GoalStatusInvalid,
        Self::GoalNotResumable,
        Self::GoalObjectiveEmpty,
        Self::GoalObjectiveTooLong,
        Self::FsAlreadyExists,
        Self::GoalUnsupportedAgent,
        Self::ApprovalExpired,
        Self::QuestionExpired,
        Self::FileExpired,
        Self::FileTooLarge,
        Self::FsTooLarge,
        Self::FsTooManyResults,
        Self::FsPathEscapesSession,
        Self::FsGrepTimeout,
        Self::FsWatchLimitExceeded,
        Self::InternalError,
        Self::PersistenceFailure,
        Self::ToolExecutionFailed,
        Self::ToolNotAvailable,
    ];

    pub const fn reason(self) -> &'static str {
        match self {
            Self::Success => "success",
            Self::ValidationFailed => "validation.failed",
            Self::RequestMalformed => "request.malformed",
            Self::AuthProvisioningRequired => "auth.provisioning_required",
            Self::AuthTokenMissing => "auth.token_missing",
            Self::AuthTokenUnauthorized => "auth.token_unauthorized",
            Self::AuthModelNotResolved => "auth.model_not_resolved",
            Self::SessionNotFound => "session.not_found",
            Self::PromptNotFound => "prompt.not_found",
            Self::MessageNotFound => "message.not_found",
            Self::ApprovalNotFound => "approval.not_found",
            Self::QuestionNotFound => "question.not_found",
            Self::TaskNotFound => "task.not_found",
            Self::FileNotFound => "file.not_found",
            Self::McpServerNotFound => "mcp.server_not_found",
            Self::FsPathNotFound => "fs.path_not_found",
            Self::WorkspaceNotFound => "workspace.not_found",
            Self::FsPermissionDenied => "fs.permission_denied",
            Self::ProviderNotFound => "provider.not_found",
            Self::ModelNotFound => "model.not_found",
            Self::TerminalNotFound => "terminal.not_found",
            Self::SkillNotFound => "skill.not_found",
            Self::SessionBusy => "session.busy",
            Self::ApprovalAlreadyResolved => "approval.already_resolved",
            Self::PromptAlreadyCompleted => "prompt.already_completed",
            Self::TaskAlreadyFinished => "task.already_finished",
            Self::McpAlreadyConnected => "mcp.already_connected",
            Self::FsIsDirectory => "fs.is_directory",
            Self::FsIsBinary => "fs.is_binary",
            Self::FsGitUnavailable => "fs.git_unavailable",
            Self::QuestionDismissed => "question.dismissed",
            Self::CompactionUnable => "compaction.unable",
            Self::SessionUndoUnavailable => "session.undo_unavailable",
            Self::SkillNotActivatable => "skill.not_activatable",
            Self::GoalAlreadyExists => "goal.already_exists",
            Self::GoalNotFound => "goal.not_found",
            Self::GoalStatusInvalid => "goal.status_invalid",
            Self::GoalNotResumable => "goal.not_resumable",
            Self::GoalObjectiveEmpty => "goal.objective_empty",
            Self::GoalObjectiveTooLong => "goal.objective_too_long",
            Self::FsAlreadyExists => "fs.already_exists",
            Self::GoalUnsupportedAgent => "goal.unsupported_agent",
            Self::ApprovalExpired => "approval.expired",
            Self::QuestionExpired => "question.expired",
            Self::FileExpired => "file.expired",
            Self::FileTooLarge => "file.too_large",
            Self::FsTooLarge => "fs.too_large",
            Self::FsTooManyResults => "fs.too_many_results",
            Self::FsPathEscapesSession => "fs.path_escapes_session",
            Self::FsGrepTimeout => "fs.grep_timeout",
            Self::FsWatchLimitExceeded => "fs.watch_limit_exceeded",
            Self::InternalError => "internal.error",
            Self::PersistenceFailure => "persistence.failure",
            Self::ToolExecutionFailed => "tool.execution_failed",
            Self::ToolNotAvailable => "tool.not_available",
        }
    }
}

impl From<ErrorCode> for i64 {
    fn from(value: ErrorCode) -> Self {
        value as i64
    }
}

pub static ERROR_CODE_REASON: LazyLock<IndexMap<ErrorCode, &'static str>> = LazyLock::new(|| {
    ErrorCode::ALL
        .into_iter()
        .map(|code| (code, code.reason()))
        .collect()
});
