use super::{RouteSpec, route};
use crate::web::CoreOperation;

// Original: packages/kap-server/src/routes/sessions.ts, registerSessionsRoutes().
pub const ROUTES: &[RouteSpec] = &[
    route(
        "GET",
        "/api/v1/sessions",
        "/api/v1/sessions",
        CoreOperation::ListSessions,
    ),
    route(
        "POST",
        "/api/v1/sessions",
        "/api/v1/sessions",
        CoreOperation::CreateSession,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_ref}",
        "/api/v1/sessions/{session_id}",
        CoreOperation::GetSession,
    ),
    route(
        "POST",
        "/api/v1/sessions/{session_ref}",
        "/api/v1/sessions/{session_id}:archive",
        CoreOperation::SessionAction,
    ),
    route(
        "POST",
        "/api/v1/sessions/{session_id}/{tail}",
        "/api/v1/sessions/{session_id}/{tail}",
        CoreOperation::SessionNestedAction,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_id}/children",
        "/api/v1/sessions/{session_id}/children",
        CoreOperation::ListSessionChildren,
    ),
    route(
        "POST",
        "/api/v1/sessions/{session_id}/children",
        "/api/v1/sessions/{session_id}/children",
        CoreOperation::CreateSessionChild,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_id}/goal",
        "/api/v1/sessions/{session_id}/goal",
        CoreOperation::GetSessionGoal,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_id}/profile",
        "/api/v1/sessions/{session_id}/profile",
        CoreOperation::GetSessionProfile,
    ),
    route(
        "POST",
        "/api/v1/sessions/{session_id}/profile",
        "/api/v1/sessions/{session_id}/profile",
        CoreOperation::UpdateSessionProfile,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_id}/status",
        "/api/v1/sessions/{session_id}/status",
        CoreOperation::GetSessionStatus,
    ),
    route(
        "GET",
        "/api/v1/sessions/{session_id}/warnings",
        "/api/v1/sessions/{session_id}/warnings",
        CoreOperation::GetSessionWarnings,
    ),
];
